spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 836d35e1300522
    password: 9528178cc30020
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  rabbitmq:
    addresses: #Host do RabbitMQ

server:
  port: 8083

notification:
  email:
    sender: #email do remetente

broker:
  queue:
    task:
      created:
        name: tasks.v1.task-created